### ISSUE TITLE
Anyway of pulling the readings from the next link

### ISSUE THREAD

**Issue by ZeoKnight** [pazaan/decoding-contour-next-link#15]
Hi,

Thanks for the work on this - got it working without much difficulty - is it possible to get the glucose readings from the contour next link? for those who don't use the pump sensors

thanks,

**Comment by r0ller** [comment]
I also wanted to ask Pazaan about that although I could have checked the code itself;) Nevertheless, if not, it's possible and if you wish I can post some links to official Medtronic docs about it and an initial work on that you can find in my repo: https://github.com/r0ller/T1Dmon

**Comment by pazaan** [comment]
It is possible. I just added https://github.com/pazaan/decoding-contour-next-link/blob/master/read_contour_next24.py
