### ISSUE TITLE
Required to register devices at CareLink?

### ISSUE THREAD

**Issue by mortlind** [pazaan/decoding-contour-next-link#19]
I have tried using this fork (pazaan) as well as the fork of paulokow. This fork gives me  issue #18  but paulokows fork brings me all the way to getting the hmac, ut fails on getting the key from CareLink. So it struck me, that maybe my Contour Next Link and pump must be registered at CareLink for getting a key. Is this a requirement? I have not registered the devices at CareLink, since I have a hard time finding a PC which supports the requirements of CareLink.

**Comment by andyrozman** [comment]
Yes you must register your device there, so that all required information is stored there... After you have the key, you are good to go with this code.

**Comment by mortlind** [comment]
Thanks @andyrozman, very good to know. Perhaps this should be mentioned in the Readme, but probably it is obvious to everybody else. Another suggestion is that the code should report that "the device may not be registered" rather than asking to "please plug in the device". I could fix this and add a pull request.

Do you know a way of registering the device without finding a PC that requires an old FireFox or old IE with Java-support?

**Comment by paulokow** [comment]
@mortlind if you have time I saw @pazaan already removed the dependency on CareLink in Android client (see this [Commit](https://github.com/pazaan/600SeriesAndroidUploader/commit/a323eb70b191510f6f954c6c252df16ed0e73acd) ). I guess it should be possible to port, but don't have spare time at the moment.

**Comment by twain47** [comment]
I believe @pazaan has already done this work. I was able to run read_minimed_next24.py successfully without running get_hmac_and_key.py first.  I suspect it may have been resolved in this commit: https://github.com/pazaan/decoding-contour-next-link/commit/3baa0f261d3ae52b03649888a3ac89b23bb84e24 and the readme hasn't been updated.

**Comment by mortlind** [comment]
@twain47 Woah ... It works! I was only testing `read_contour_next24.py` since I have a Contour Next Link stick. Thanks for that.

**Comment by paulokow** [comment]
@twain47 thx for the hint. Indeed it does not need the db file with keys anymore.
