### ISSUE TITLE
Remote bolus and remote suspend

### ISSUE THREAD

**Issue by twain47** [pazaan/decoding-contour-next-link#20]
I know the code for doing this functionality is currently commented out but would you expect either mt.doRemoteBolus() or mt.doRemoteSuspend() functions to work or are they still a work in progress?

At the moment if I run doRemoteBolus I get a raw response of:
`0400ff010011`
and the pump does not execute anything.

If this isn't working yet would you be able to give me some information on your work so far so that I can try and continue it?

**Comment by pazaan** [comment]
Unfortunately this is a dead end for using the CNL. That response is a NAK for "Not supported". The CNL is blocking that command at the firmware. The only way we will be able to remote bolus is to build a replacement device for the CNL, and to do that, we need to reverse engineer the over-the-air encryption (which is different from the CNL USB encryption).

**Comment by r0ller** [comment]
Wow, I have just asked a related question on gitter:) Do you know if something like the TI CC2531 or CC2540 would be suitable for communicating with the pump?

**Comment by pazaan** [comment]
This one can: http://www.ti.com/tool/CC2531EMK

**Comment by 128keaton** [comment]
So, wait, the bolus function over USB is blocked in firmware? I can bolus manually, remotely, using my CNL device. Darn.

**Comment by pazaan** [comment]
@128keaton that's correct - otherwise we'd already have 600-series pumps working with Loop or OpenAPS 😉

**Comment by 128keaton** [comment]
@pazaan that is amazingly frustrating. I enjoy my 600 series pump but I'd love to not have to keep pulling it out to use it. Hmm. I wish I could be of more help.

**Comment by pazaan** [comment]
@128keaton agreed! A bunch of embedded devs are already working on breaking the encryption on 600-series so that we can free our users from the pump UI, and enable other closed loop options.

**Comment by 128keaton** [comment]
@pazaan thats great. Is there a community where I can go and volunteer to test, etc? I just jumped into this on a whim today and I'm really surprised to see how much support/ideas there are out there. I just wish we had a bit more control over our CNLs.

**Comment by pazaan** [comment]
There's not really any testing to do as such. Currently it's at a stage of a bunch of engineers attempting to reverse engineer crypto. Once the crypto is broken, I don't think much testing will be required, because the protocol is already known, and working. If you have any experience in this area, let me know and I can point you at the appropriate Gitter channel.

**Comment by maristal** [comment]
I'm an embedded engineer who would be interested to join the gitter channel, if its still active

**Comment by pazaan** [comment]
@maristal You can join the channel. Just search for it in Gitter :)
