### ISSUE TITLE
Switch to Python3

### ISSUE THREAD

**Issue by mortlind** [pazaan/decoding-contour-next-link#23]
Preparations for supporting Python3 have already started with changing print syntax and module names. A lot of IO-specific Python3 conversion is remaining for actually running under Python3. Supporting Python3 and Python2 may not be simultaneously possible, so probably a separate py3-branch must be established.

**Comment by paulokow** [comment]
@mortlind , could you be more specific on the issues you face when running on Python 3? Some log would be helpful.

**Comment by mortlind** [comment]
The following example is directly from the repo of @pazaan master. There is a whole range of such string-to-bytes conversions to do when switching from Python2 to Python3. All Python3 IO works with byte arrays, as far as I have understood, while all Python2 IO works with strings.
```
ml@diapi:~/decoding-contour-next-link-pazaan $ python3 -i read_minimed_next24.py
2017-10-23 13:31:27,900 INFO [__main__] # Opening device
2017-10-23 13:31:27,938 INFO [__main__] Manufacturer: Bayer HealthCare LLC
2017-10-23 13:31:27,943 INFO [__main__] Product: Contour Link USB Device
2017-10-23 13:31:27,947 INFO [__main__] Serial No: 0000000001004354
2017-10-23 13:31:27,948 INFO [__main__] # Read Device Info
2017-10-23 13:31:27,949 INFO [__main__] # Closing device
Traceback (most recent call last):
  File "read_minimed_next24.py", line 1320, in <module>
    downloadPumpSession(pumpDownload)
  File "read_minimed_next24.py", line 1217, in downloadPumpSession
    mt.getDeviceInfo()
  File "read_minimed_next24.py", line 795, in getDeviceInfo
    self.sendMessage( struct.pack( '>B', 0x58 ) )
  File "read_minimed_next24.py", line 782, in sendMessage
    message = struct.pack( '>3sB', self.MAGIC_HEADER, len( packet ) ) + packet
struct.error: argument for 's' must be a bytes object
>>> 
```

**Comment by paulokow** [comment]
@mortlind, i managed to make needed changes. Please test the commit bf6cef6389b7cafaa05060d4f261e513e225c63e as well before I merge to the master

**Comment by mortlind** [comment]
That sounds wonderful! I will test tonight.

**Comment by mortlind** [comment]
Getting status worked, but when I tried to get sensor events I got the exception below. Mind that the downloadoperations function is not made to be really used, so I had to make my own which may be the problem. I do not believe it is, since getting status worked. 
'''
  File "/home/ml/.local/lib/python3.5/site-packages/dcnl/read_minimed_next24.py", line 1149, in processPumpHistory
    historyEvents += self.decodeEvents(decodedBlocks)
  File "/home/ml/.local/lib/python3.5/site-packages/dcnl/read_minimed_next24.py", line 1142, in decodeEvents
    eventList.extend(NGPHistoryEvent(eventData).eventInstance().allNestedEvents())
  File "/home/ml/.local/lib/python3.5/site-packages/dcnl/pump_history_parser.py", line 441, in allNestedEvents
    vctr = vctr)
  File "/home/ml/.local/lib/python3.5/site-packages/dcnl/pump_history_parser.py", line 459, in __init__
    self.timestamp = timestamp
AttributeError: can't set attribute
'''

**Comment by mortlind** [comment]
The following diff fixed the issue with the SensorGlucoseReading, where I removed the `source` method and removed the base class.

```
@@ -442,7 +442,7 @@ class SensorGlucoseReadingsEvent(NGPHistoryEvent):
             pos += 9;
 
 
-class SensorGlucoseReading(NGPHistoryEvent):
+class SensorGlucoseReading: # (NGPHistoryEvent):^M
     def __init__(self, 
                  timestamp, 
                  dynamicActionRequestor, 
@@ -482,10 +482,10 @@ class SensorGlucoseReading(NGPHistoryEvent):
             self.isig,
             self.rateOfChange)
 
-    @property
-    def source(self):
-        # No idea what "source" means.
-        return BinaryDataDecoder.readByte(self.eventData, 0x01)# self.eventData[0x01];
+    # @property^M
+    # def source(self):^M
+    #     # No idea what "source" means.^M
+    #     return BinaryDataDecoder.readByte(self.eventData, 0x01)# self.eventData[0x01];^M
 
     @property
     def size(self):
```

**Comment by mortlind** [comment]
Another minor issue is that Python3 should use relative import for packages and modules within the same top-level package:

```
--- a/pump_history_parser.py
+++ b/pump_history_parser.py
@@ -1,4 +1,4 @@
-from helpers import DateTimeHelper, BinaryDataDecoder, NumberHelper
+from .helpers import DateTimeHelper, BinaryDataDecoder, NumberHelper^M
 import struct
 from datetime import timedelta
```

and

```
--- a/read_minimed_next24.py
+++ b/read_minimed_next24.py
@@ -19,9 +19,9 @@ import hashlib
 import re
 import pickle # needed for local history export
 import lzo # pip install python-lzo
-from pump_history_parser import NGPHistoryEvent
-from pump_history_parser import BloodGlucoseReadingEvent
-from helpers import DateTimeHelper
+from .pump_history_parser import NGPHistoryEvent
+from .pump_history_parser import BloodGlucoseReadingEvent
+from .helpers import DateTimeHelper
 
 logger = logging.getLogger(__name__)
 
```

**Comment by paulokow** [comment]
@mortlind , thx for the feedback.
The issues with `SensorGlucoseReading` fixed with cd69271ef2f95b7c114d77115756c510ba39432d
It's first time ever I use python 3 so I did not know overloading of properties works different as well.

On relative modules or not it's far from easy topic. 
We'd need to do deeper refactoring to make a package out of everything but `__main__`
For now one has to use PYTHONPATH if using as a library

**Comment by mortlind** [comment]
@paulokow I think the changes I suggested regarding the relative imports are sufficient. It only pertains to the modules imported which are from the same package. It is true that then the top level package must be in the path. Alternatively you must have '' in the path. However, I am using the repo as a library in a Pyro service application, which then is used by a Flask-based web-application that I connect to from my phone or laptop. This is very useful, and suggest that you continue developing it as a library, and then establish a separate repo, or just a sibling folder, with scripts. Refactoring does not need to go very deep. Anyways, these are just my suggestions based on my use scenario.

**Comment by mortlind** [comment]
@paulokow I know it is a bit more tedious, but you can run the module `read_minimed_next24` in the top level package `decoding-contour-next-link` if your cwd is the directory with the package. Then you issue 
```$ python3 -m  decoding-contour-next-link.read_minimed_next24```

**Comment by paulokow** [comment]
@mortlind thx. It works this way indeed.
Commited with 6e65489cb9755125369d95c33099b63d48b68072
I also use it as a module but on python 2.7 there was no issue. After change seems to work on both.
