### ISSUE TITLE
Hard coded test hid?

### ISSUE THREAD

**Issue by sdish** [pazaan/decoding-contour-next-link#29]
Hello,

I've been trying to get setup running ```read_contour_next24.py``` but I get the exception on L82 about not having hard coded test hid. Probably I'm missing something obvious, but could someone explain what I'm doing wrong?

Thanks!

**Comment by paulokow** [comment]
Hi,  yhis script does not work.

Ppease use, as in README (from parent folder):
 python -m decoding-contour-next-link.read_minimed_next24
