### ISSUE TITLE
Unable to get HMAC and key

### ISSUE THREAD

**Issue by githubadas** [pazaan/decoding-contour-next-link#4]
Hi Lennart,

We try to run you script in PL. I hope it will be works at all :) Great work!
At this moment I have problem with getting hmac and key. Starting script I receive below info:

root@PC:/home/diabetes/decoding-contour-next-link# python get_hmac_and_key.py MinimedUser
Enter the password for the CareLink user MinimedUser: 
Traceback (most recent call last):
  File "get_hmac_and_key.py", line 92, in <module>
    ( int1, key, count ) = request.decodeResponse( response.raw.read() )
  File "get_hmac_and_key.py", line 31, in decodeResponse
    keyArray = decoder.readObject()
  File "/home/diabetes/decoding-contour-next-link/javaobj.py", line 261, in readObject
    opcode, res = self._read_and_exec_opcode(ident=0)    # TODO: add expects
  File "/home/diabetes/decoding-contour-next-link/javaobj.py", line 289, in _read_and_exec_opcode
    (opid, ) = self._readStruct(">B")
  File "/home/diabetes/decoding-contour-next-link/javaobj.py", line 302, in _readStruct
    raise RuntimeError("Stream has been ended unexpectedly while unmarshaling. (%d vs %d)" % (len(ba), length))
RuntimeError: Stream has been ended unexpectedly while unmarshaling. (0 vs 1)
root@PC:/home/diabetes/decoding-contour-next-link# 

Can you give me some advice?

Pawel.
OS: Ubuntu 16.04

**Comment by pazaan** [comment]
Hey Pawel,

Is your CareLink user actually called "MinimedUser"?

**Comment by githubadas** [comment]
No :) I just change for this site. In script I use correct username and pass :)

**Comment by pazaan** [comment]
I just repro'd this error by entering a serial number that CareLink didn't like (only 4 digits). Is there a way you can get me the output of your sqlite database file? You can find and DM me on Gitter.

**Comment by pazaan** [comment]
This is a bug with the script - I assumed that the "long serial" always started with 6213 - in this case, it was 6214. I have to update the script to get the "long serial" from the USB stick itself.
