### ISSUE TITLE
Cannot find lzo.lib for pip install python-lzo

### ISSUE THREAD

**Issue by sophieroos** [pazaan/decoding-contour-next-link#41]
For running `pip install python-lzo` I need to have lzo.lib, but it is something that I can nowhere find. Can you help me? Part of the error I get is:

> LINK : fatal error LNK1181: cannot open input file 'D:\Downloads\lzo-2.09\lzo.lib'
>     error: command 'C:\\Users\\Sophie\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\x86_amd64\\link.exe' failed with exit status 1181

Where can I find `lzo.lib` or is it something that I can generate? What is its content?

I hope you can help me.

**Comment by pazaan** [comment]
It looks like for Windows that you'll need to install the LZO library. In this case, in `D:\Downloads\lzo-2.09`. See the instructions [here](https://github.com/jd-boyd/python-lzo#windows)
