### ISSUE TITLE
Run one contour 2.4 in two different pumps

### ISSUE THREAD

**Issue by grlcastro** [pazaan/decoding-contour-next-link#43]

**Comment by grlcastro** [comment]
Is it possible change the code, to have one contour, pushing the info from two different pumps?
I have to two T1d, just wondering if it is possible...

**Comment by pazaan** [comment]
It's not really feasible to do this. A Contour will only allow itself to be paired to one pump at a time (though it is possible for a pump to be paired with multiple Contours).
It's possible to use ad-hoc connections, but then you'd need to accept the connection request on the pump every five minutes, which defeats the purpose of low maintenance monitoring ;)

**Comment by mortlind** [comment]
A related question, which I have often speculated about, but not had the situation which required it: If I connect two NextLinks to my PC, how may I control from the software which if them to address? I admit that I have no thoroughly investigated before throwing this question out, and for that I apologize ...

**Comment by pazaan** [comment]
@mortlind there's nothing in the code to support two CNLs on the same PC. Code would have to be modified to support this.

**Comment by grlcastro** [comment]
I just want to make sure that was never tried before.
thanks

**Comment by mortlind** [comment]
@pazaan I will try to look into it. I seems possible, but requires some re-design. It would help me increase the coverage in my house ...
