### ISSUE TITLE
Special BGL status codes

### ISSUE THREAD

**Issue by ondrej1024** [pazaan/decoding-contour-next-link#45]
Hi @pazaan , thanks a lot for reverse engineering the CNL protocol and providing the Python implementation. 

I have recently started the Python based project [dd-guard](https://github.com/ondrej1024/ddguard) to get real time bloop glucose and pump data from the 670G on a Smartphone app which is based on your protocol implementation.

During testing I noticed that the 670G reports certain events as special BGL status codes which are actually just ridiculously high glucose values. I was able to associate the following values to these events:
```
BGL_VALUE_TOOLOW    = 777
BGL_VALUE_CHANGE    = 773
BGL_VALUE_UPDATING  = 771
BGL_VALUE_CALIBRATE = 770
BGL_VALUE_WAITING   = 769
```
There are some values missing and I was wondering if you have the complete list of these codes. I checked the protocol doc [here](https://github.com/tidepool-org/uploader/blob/master/lib/drivers/medtronic600/docs/packetStructure.md) but couldn't find them there either.

Thanks.

**Comment by Pogman** [comment]
These are easier when read as HEX: 0x0300 with the upper byte being the exception flag, lower the exception code.

0x0300 SENSOR_OK
0x0301 SENSOR_INIT
0x0302 SENSOR_CAL_NEEDED
0x0303 SENSOR_ERROR
0x0304 SENSOR_CAL_ERROR
0x0305 SENSOR_CHANGE_SENSOR_ERROR
0x0306 SENSOR_END_OF_LIFE
0x0307 SENSOR_NOT_READY
0x0308 SENSOR_READING_HIGH
0x0309 SENSOR_READING_LOW
0x030A SENSOR_CAL_PENDING
0x030B  SENSOR_CHANGE_CAL_ERROR
0x030C SENSOR_TIME_UNKNOWN

More info here:

https://github.com/pazaan/600SeriesAndroidUploader/blob/ae33d79ac93b203e9108edd91152d6973ed00189/app/src/main/java/info/nightscout/android/history/PumpHistoryParser.java#L1725

**Comment by ondrej1024** [comment]
That was quick, thanks a lot.
