### ISSUE TITLE
Uploader for 780G?

### ISSUE THREAD

**Issue by mortlind** [pazaan/decoding-contour-next-link#54]
My daughter just switched from 670G, which works with the Contour Next Link, to the 780G, which supposedly does not. Is there any change that this library will work with the new bluetooth-based interface of the 780G? Or are there other, similar libraries that will?

**Comment by pazaan** [comment]
To my knowledge, no-one has reversed engineered the Bluetooth comms. I don’t have a 780G myself, so if support were to end up in this project, it would be a contribution from elsewhere.
